---
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
  become: true

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    daemon_reload: true
    state: restarted
  become: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
