---
- name: Clear old admin config file
  ansible.builtin.file:
    path: /etc/kubernetes/admin.conf
    state: absent
  become: true

- name: Regenerate admin.conf
  ansible.builtin.command: >
    kubeadm init phase kubeconfig admin --kubeconfig-dir=/etc/kubernetes --apiserver-advertise-address={{ public_ip }}
  become: true

- name: Fetch admin.conf to local machine
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ local_kubeconfig_path }}"
    flat: true
  become: true
