---
- name: Delete the MyAIOps test infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - role: ec2
      tags: [ ec2 ]
    - role: volumes
      tags: [ volumes ]
    - role: vpc
      tags: [ vpc ]
