---
- name: Get VPC info
  ansible.builtin.import_role:
    name: vpc
    tasks_from: get_vpc_info.yaml

- name: Get EC2 AMI info
  include_tasks: get_ami_info.yaml

- name: IAM role and instance profile are present
  include_tasks: iam_present.yaml

- name: EC2 instances are present
  include_tasks: ec2_present.yaml

- name: Remove AWS resources.
  tags: [never, delete]
  block:
    - name: Include tasks in ec2_absent.yaml.
      include_tasks: ec2_absent.yaml
